name: Build master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Build and install dependencies
        run: |
          python -m pip install --upgrade pip
          python setup.py develop

      - name: Lint with flake8
        run: |
          pip install flake8
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # The exit-zero flag treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Update webpage
        run: |
          cov19vis
          mv index.html docs/index.html
          mv confirmed* docs/assets/images/confirmed/

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Chris Campo
          author_email: ccampo133@users.noreply.github.com
          message: Auto-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
