name: Scheduled auto-update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Build and install dependencies
        run: |
          python -m pip install --upgrade pip
          python setup.py develop

      - name: Update webpage
        run: |
          cov19vis
          mv index.html docs/index.html
          mv confirmed* docs/assets/images/confirmed/
          mv daily_confirmed* docs/assets/images/confirmed/
          mv death* docs/assets/images/deaths/
          mv daily_death* docs/assets/images/deaths/

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Chris Campo
          author_email: ccampo133@users.noreply.github.com
          message: Scheduled auto-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
